vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<leader>w", "<cmd>w<cr>")
vim.keymap.set("n", "<leader>q", "<cmd>q<cr>")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set({ "n", "v" }, "<cr>", function() vim.treesitter.select("parent") end)
vim.keymap.set("v", "<bs>", function() vim.treesitter.select("child") end)
